### ISSUE TITLE
[FEATURE] Websockets for Endpoints

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#106]
The endpoints of the API could trigger Websocket-Events on which Front-end-Applications could listen

**Comment by eddiejaoude** [comment]
Yep, we will definitely need this for the map UI project

**Comment by BOLT04** [comment]
@Cahllagerfeld this seems like a cool feature, is it still needed?

**Comment by Cahllagerfeld** [comment]
I dont know how @eddiejaoude planned with this. In my opinion its still needed. I think theres even a nest-package for Websockets `@nestjs/websockets @nestjs/platform-socket.io`. The last time I had a look at websockets with nestjs there was an issue that the packages wasnt compatible with the newest socket.io-version. I think there needs to be some research done on it first before implementing.

What do you think about that Eddie?

**Comment by eddiejaoude** [comment]
yep I am definitely keen on this feature 👍 we could do a prototype / spike on a live stream 🤓
