### ISSUE TITLE
Who can update/delete data?

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#107]
> I think we should protect the details to be the author of the resource, what do you think? this can come in another issue + PR

> We would probably have to handle this with a query-parameter if this is allowed

> A payload within a DELETE request message has no defined semantics;
sending a payload body on a DELETE request might cause some existing
implementations to reject the request.

> Good idea 👍

> Or maybe we only allow admin users to delete as that might be easier. We should probably raise an issue and add this discussion there

Initial conversation https://github.com/EddieHubCommunity/api/pull/105

/cc @Cahllagerfeld

**Comment by Cahllagerfeld** [comment]
Do we need a role-management then, or who do you consider to be a admin? 😅

**Comment by eddiejaoude** [comment]
To keep things simple, I am thinking data only gets created/updated/deleted by the Discord bot, so we can use the Discord roles and author from there. What do you think?

**Comment by Cahllagerfeld** [comment]
> To keep things simple, I am thinking data only gets created/updated/deleted by the Discord bot, so we can use the Discord roles and author from there. What do you think?

If its only the bot, thats probably the best viable way. Then we just have to think of a way on how to validate the actual discord roles in the guard

**Comment by eddiejaoude** [comment]
## Modules

**discord**
- change `discordUser` to `DiscordAuthor.uid` (also have `DiscordAuthor.platform`)
- update/delete check for `uid`

**standup**
- change `discordUser` to `StandupAuthor.uid` (also have `StandupAuthor.platform`)
- delete check for `platform` + `uid`

**calendar**
- delete/update check for `platform` +`uid`

**github**
- [x] information from GitHub's API

**Comment by Cahllagerfeld** [comment]
short update: 

- [x] functionlity works since yesterday
- [ ] e2e-tests need new step-defintion
