### ISSUE TITLE
add description and author to package.json

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#109]

**Comment by Kritika-2000** [comment]
@Cahllagerfeld   Sir! can I work on this issue ? Can you tell me what name and description you want so that I can add it ?

**Comment by Cahllagerfeld** [comment]
I think
**description**:  `An API to manage our community data`
**author**: ` EddieHubCommunity `

What do you think @eddiejaoude

**Comment by Kritika-2000** [comment]
ok so can I work on it ?

**Comment by Cahllagerfeld** [comment]
sure 👍

**Comment by Cahllagerfeld** [comment]
closed with #111
