### ISSUE TITLE
Standup endpoint

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#11]
It would be great to encourage more daily standup information. 

- Save (from bot or UI) daily standup information
- Read daily standup information in daily order desc

---

Update after discussion with @mstanciu552 below

> send the information from EddieBot to the API using axios or fetch and then save them in a users collection in our db

**Comment by mstanciu552** [comment]
I have a question that would help with this. Specifically with the information from the _discord bot_.

How would we get the standup from it? Is it something from discord.js or do we need to use the Discord API?

**Comment by eddiejaoude** [comment]
We have a command `^standup <yesterday> || <today>` it is nothing technically special, it just rewrites the message as a notifications

**Comment by mstanciu552** [comment]
Oh I see so we could just send the information from EddieBot to the API using `axios` or `fetch` and then save them in a users collection in our db.

Is thus the kind of system you are talking about?

**Comment by eddiejaoude** [comment]
yes that is correct - sorry if I explained it badly, thank you for challenging 👍 - I will update the description

**Comment by mstanciu552** [comment]
Thanks for helping me to understand. :smile:

**Comment by Vyvy-vi** [comment]
I think, perhaps we could simplify this and avoid using discord API?
We could have the bot store this on Mongo and then the site could render the content from there?

**Comment by eddiejaoude** [comment]
Yep 👍 the bot will send the data to our API which will store the data in the db

**Comment by mstanciu552** [comment]
This is a suggestion. If you think of anything better please let us know.

We could have a variable in the `.env` file that points to the URL of the API. Then using `axios`(or `fetch`) we make a request.

Then in the API we modify the `User` model to also have a standup array. 

Please share your suggestions.  😄 👍

**Comment by eddiejaoude** [comment]
Yep the API url in the Bot and UI will be part of the config, as this will change depending if we are developing locally or in production etc.

Yep, the `User` model will have a standup array 👍

**Comment by mstanciu552** [comment]
This question might be a bit redundand.

Does the `^standup` command also send the user that called it?

**Comment by Vyvy-vi** [comment]
It only sends the message in the channel it is called in

**Comment by mstanciu552** [comment]
Oh .... Do you also know if there is any way to get the sender through discord.js?

Something like `message.from`?

**Comment by Vyvy-vi** [comment]
`message.author` should return the member object for the sender of the message

**Comment by mstanciu552** [comment]
Alright so I tested how to get the user.
![Screenshot (89)](https://user-images.githubusercontent.com/34579048/105340553-b7d92880-5be6-11eb-9426-aae3823794de.png)
This will make an object with the id, username and discriminator(the `#` followed by 4 digits near the username).
We could create Users in the db based on this information, to which we add their standup array.(this could also have a date attached to it)

Share you opinions. It really help. Thank you. 👍 😄

**Comment by eddiejaoude** [comment]
Nice 👍 , yes we will need to send the user with the standup message - so we can save the standup message against the user 

Currently the Discord user API is being created, so we can move things to the API

**Comment by Cahllagerfeld** [comment]
I could potentially do this.
- I think we handle this like the `discord`-Service where data is stored in an Array until we have a database I'd suggest.
- Do we need a Put-Endpoint for Editing Standups?

**Comment by eddiejaoude** [comment]
Thanks @Cahllagerfeld 👍 . Good question, I do not think we need a `PUT` endpoint

**Comment by eddiejaoude** [comment]
PR merged
