### ISSUE TITLE
[Discussion] Api Microservices

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#113]
We're currently building a monolithic application which nearly doesn't scale at all.
Wouldn't it be better to implement it as microservices, or would the api would get too complex for the requirements the project needs to fullfill?

It's just for discussion not for implementation

**Comment by eddiejaoude** [comment]
It makes some things simpler and other things more complicated. It would be interesting to hear peoples thoughts on this. As it is still quite small at the moment, I would suggest keeping it as a single repo and service, then in the future we can look to split it out if needed as we understand the requirements more

**Comment by Cahllagerfeld** [comment]
I like the idea of building a dockerized microservice cluster. But as you said I'm not sure if thats a little overkill for the current app. When deciding to split the project to microservices, we need to make some architectural decisions like using a discovery-service, using a message broker, etc...

**Comment by BOLT04** [comment]
> I would suggest keeping it as a single repo and service, then in the future we can look to split it out if needed as we understand the requirements more

I agree with @eddiejaoude in keeping it as it is, then if we reach a point where we start having problems with the current architecture, we discuss how to **evolve** it. In my opinion, microservices architecture is a viable option when we have a really good reason to do it. What would be the outcome and benefits of using it right now? What are the problems we are trying to solve?
I don't know much about the project, but from what I see there isn't a need for asynchronous processing. Therefore, there isn't a need for adding a message broker, but correct if I'm wrong, please.

Currently, this seems to be the architecture of this project:
![imagem](https://user-images.githubusercontent.com/18630253/132946840-6181b1a4-6a06-4b58-9fd5-b4804c348895.png)

The purpose of the API is to receive requests and return the data the client wants. It has an HTTP interface and possibly a WebSocket interface as well in the future. I'd argue it is simple enough to be a monolith for now.

> We're currently building a monolithic application which nearly doesn't scale at all.

@Cahllagerfeld I'm interested in knowing why the API doesn't scale currently, could you elaborate on this?
Is the problem related to horizontally scaling the DB or the web servers, or is it something else?

Again, this is only my take on this 🙂, I'd love to hear more opinions on this topic!

**Comment by BOLT04** [comment]
@Cahllagerfeld and @eddiejaoude, any thoughts on this 🙂?

**Comment by Cahllagerfeld** [comment]
I'd definitely postpone this until the rewrite is finished 🤔
