### ISSUE TITLE
Refactor Initilaize logic

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#117]
> I did generate all the tokens reading their documentation, but still getting the same issue, do GitHub codespaces support docker-compose, Or should I install linux.

I just tested it using AstraDB in the cloud and it worked, but I noticed that if the `.env` file contains any of the `STARGATE_*` config then it is looking for the local database not in the cloud, even if the config for the cloud is set.

So I suggest removing any config in `.env` that has `STARGATE_*` and so it should only have...

```bash
APPROVED_TOKENS=abc,def
DEBUG=false

ASTRA_APPLICATION_TOKEN="AstraCS: ..."
ASTRA_DATABASE_ID=""
ASTRA_DATABASE_REGION="europe-west1"
```

_Originally posted by @eddiejaoude in https://github.com/EddieHubCommunity/api/issues/108#issuecomment-853929691_

**Comment by eddiejaoude** [comment]
Good idea 👍 - I think that lowers the barrier to entry, because then all people need to do is log in to AstraDB with their Github account and they can get it working 👍 

good idea @Cahllagerfeld 💥

**Comment by Cahllagerfeld** [comment]
I had a thought about this. Here are my thoughts
1. we need the `STARGATE_*`-env variables because we're using the `cp`-Command in order to make the tests in the actions work properly, I think we cant leave them away.
2. In my opinion it should be enough to adjust the Readme with a section `setup locally` or `setup with datastax` and tell there which `env-variables` need to be deleted in order to make it run in the cloud or locally.

**Comment by Cahllagerfeld** [comment]
Stargate related tickets aren't relevant anymore, so closed

**Comment by eddiejaoude** [comment]
Thanks Cahl 👍
