### ISSUE TITLE
Fix Swagger for Kubernetes Deployment

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#126]
The Deployed version of the API has problems displaying the swagger-documentation. We should take a look at it.

**Comment by eddiejaoude** [comment]
Deployed
http://api.eddiehub.org/swagger/ (shows blank page)

Locally
http://localhost:3000/swagger (works fine)

- [ ] Run container locally and see if swagger has an issue or not

**Comment by Cahllagerfeld** [comment]
In `main.ts` 
this 
```ts
app.use(helmet());
```
needs to be this
```ts
  app.use(helmet({contentSecurityPolicy: false}));
```
