### ISSUE TITLE
fix the commented test

### ISSUE THREAD

**Issue by iason9** [EddieHubCommunity/api#141]
fix the test : And the response should be "Welcome to EddieHub! Currently running version: v0.0.0" in : test/features/hello-world.feature

**Comment by Cahllagerfeld** [comment]
the corresponding PR is merged, can this be closed then?

**Comment by iason9** [comment]
okay closed it !

**Comment by eddiejaoude** [comment]
I think the end-to-end test has not been updated for this yet
