### ISSUE TITLE
Make Modules configurable

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#157]
The modules of the API needs to be configurable.

The configuration should be stored within the database.

_Originally posted by @eddiejaoude in https://github.com/EddieHubCommunity/EddieBot/issues/573#issuecomment-874805732_

**Comment by Cahllagerfeld** [comment]
We should handle the case if theres no config provided in the DB as well

**Comment by eddiejaoude** [comment]
Thank you for raising 👍

**Comment by Cahllagerfeld** [comment]
I'd put the configs in a own collection. Because of that I'd probably handle the Config-Logic in a own Module. What would be a good name for that module? I think we cant use `ConfigModule` as this is provided from the Nest-package.

**Comment by eddiejaoude** [comment]
Good question 🤔 

What about `ConfigDataModule`? 🤷‍♂️

**Comment by Cahllagerfeld** [comment]
Maybe this Issue should be split up into several smaller ones to prevent the PRs from getting to back. I think this issue might be more work than it looks at first glance

**Comment by eddiejaoude** [comment]
Yep, we could split it up per module

**Comment by Cahllagerfeld** [comment]
I think thats not relevant anymore either, because we dont want to run a multi-tenant approach anymore
