### ISSUE TITLE
Use new Project-Boards

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#158]
We could have a look and use the new Project-Boards github provides. While Eddiebot and the API are growing together many issues from the projects depend on each other, so we need a way to organize who works on which issue in which project to not loose the overview.

**Comment by eddiejaoude** [comment]
Love this idea 👍 

I think it would make a good live stream for us all to have a play with the new project boards 🤓

**Comment by BOLT04** [comment]
Hi everyone 😃, awesome idea @Cahllagerfeld 👍. This new projects board is a new feature in GitHub right?
I checked it [here](https://github.com/features/issues) and I think we would have to signup for the beta, or have we done that already?

**Comment by Cahllagerfeld** [comment]
You can have a look in the eddiehub-community boards. We have early access. I already created one for Api & Eddiebot, but Eddie wanted to cover the project board topic in a stream

**Comment by BOLT04** [comment]
awesome, thank you @Cahllagerfeld 🙂
