### ISSUE TITLE
Add AsciiDoc for Documentation?

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#161]
Should we add Ascii-Doc for Documentation (Auth-Flow, etc...) or is Swagger and standard `Readme` enough for this?

**Comment by eddiejaoude** [comment]
Good question 🤔 

I think we might need AsciiDoctor to help write some proper documentation, that can then reference Swagger - we don't want to duplicate but them to complement each other

**Comment by Cahllagerfeld** [comment]
I think this can be set up. The documentation itself is in #174.
The setup can be found in [this](https://github.com/eddiejaoude/stargate) repo
