### ISSUE TITLE
Update Nestjs v8

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#162]
Nestjs released a new major version with new features and deprecations. Maybe we should upgrade our dependencies to match the new version

**Comment by eddiejaoude** [comment]
oh interesting, yes 👍

**Comment by Cahllagerfeld** [comment]
I'd do that after the current PR is merged, because otherwise we may run into many many conflicts with the dependencies

**Comment by eddiejaoude** [comment]
Sounds like a good plan 👍
