### ISSUE TITLE
[IDEA] Livemap Todos

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#175]
Maybe we can collect the things that need to be done before the Livemap is implementable here.
I think when we're starting to collect data this will be one of the next milestones

**Comment by eddiejaoude** [comment]
yep, this will be next 👍 

For the map, I we have most of the data:
- location (set by the Discord bot command or either from their GitHub profile)
- profile picture
- events from GitHub and Discord

**Comment by mikeysan** [comment]
To make it easier for anyone who missed the meeting to follow, is there a discussion that this issue can be linked to?
