### ISSUE TITLE
[OTHER] Add Link to Ascii-Doc Documentation in repo

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#181]
### What would you like to share?

Currently the Link to the Ascii-Doc isnt public in the repo. We should change that

**Comment by syedareehaquasar** [comment]
@Cahllagerfeld I would like to work on this issue can u please help me with a reference like I couldn't find ASCII-doc in docs (not sure it's not public that is why I am not able to view it)
