### ISSUE TITLE
[OTHER] Clean Branches

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#182]
### What would you like to share?

I think we're having quite a few stale branches which are already merged. We should probably delete the merged branches to avoid confusion

**Comment by eddiejaoude** [comment]
oh yes 17 is quite high, I can take a look

**Comment by Cahllagerfeld** [comment]
awesome! 💥

**Comment by krishguptadev** [comment]
Cool! Wish I could help!!
