### ISSUE TITLE
[BUG] token expiration

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#183]
### 🙁 Actual behavior

currently the [token-expiration](https://github.com/EddieHubCommunity/api/blob/1b091078ca161410f970978f74da234fbebce34c/src/auth/auth.service.ts#L35) is still hardcoded. 

### 🙂 Expected behaviour

Maybe in a future bugfix we should make this configurable with a bot-command and add a default-fallback

**Comment by eddiejaoude** [comment]
Oh yes! Thank you for raising 👍

**Comment by Cahllagerfeld** [comment]
closed do to mongo-migration. Tokens aren't needed anymore
