### ISSUE TITLE
[BUG] Not Return 400 with invalid token

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#185]
### 🙁 Actual behavior

When [validating a token](https://github.com/EddieHubCommunity/api/blob/1b091078ca161410f970978f74da234fbebce34c/src/auth/auth.controller.ts#L59) a `400` gets returned in case the token is invalid.
I tried to implement this feature yesterday to the bot - Problem is when returning a 400 its treated like an exception which means that we need to catch it in the Bot.

### 🙂 Expected behaviour

In my opinion we should return `200` as the operation on the server was executed successfully, but only with the result, that the token is not valid

**Comment by eddiejaoude** [comment]
Oh yes, good spot 🤓  yep returning a `200` with an invalid message is probably best 👍
