### ISSUE TITLE
[FEATURE] Startup with docker-compose

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#191]
Awesome! Thank you @Cahllagerfeld !!

>  The docker-compose needs to wait until the Stargate-Container runs before the Api can be started. This issue isnt Gitpod related, but I'm not deep enough into docker-compose to solve this straight.

No problem, we can ask for help on this, I think there is `depends_on` property. Is a wait really needed though because I think the API does not make a connection to Stargate until a http request hits the API?

Docs https://docs.docker.com/compose/startup-order/

_Originally posted by @eddiejaoude in https://github.com/EddieHubCommunity/EddieBot/issues/601#issuecomment-899089484_

Currently we create the Client for accessing in the constructor. This means if this fails the API wont start.

In my opinion this is correct, because otherwise we could start the API successfully and without warning although we arent having a database connection. What do you think about it?

**Comment by eddiejaoude** [comment]
> oh you used depends_on already 🎉 - I think the API will wait for stargate to be ready

I think it should wait because of the `depends_on`? we might need to check / test
