### ISSUE TITLE
[FEATURE] Change Collections to Arrays

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#195]
### ⭐ Suggestion

Currently the response from Astra gets just retunred. We should think of mapping the responses to arrays.

**Comment by BOLT04** [comment]
Hi @Cahllagerfeld  👋, could you provide some examples where Collections would change to arrays?
Are these changes made to the `astra.service.ts` file?

**Comment by Cahllagerfeld** [comment]
Currently the data from Astra is returned like this
```json
{
  "bf05322f-0e6d-4f0c-85cb-2dd8ee620d2f": {
    "author": {
      "platform": "discord",
      "uid": "string"
    },
    "createdOn": "2021-09-05T13:27:05.718Z",
    "todayMessage": "string",
    "yesterdayMessage": "string"
  }
}
```

The idea was to turn it into something like this
```json
[
   {
      "id":"bf05322f-0e6d-4f0c-85cb-2dd8ee620d2f",
      "author":{
         "platform":"discord",
         "uid":"string"
      },
      "createdOn":"2021-09-05T13:27:05.718Z",
      "todayMessage":"string",
      "yesterdayMessage":"string"
   }
]
```

The adjustments need to be done in [this](https://github.com/EddieHubCommunity/api/blob/main/src/astra/astra.service.ts) file

**Comment by eddiejaoude** [comment]
@Cahllagerfeld is this still needed?

**Comment by Cahllagerfeld** [comment]
It's from the older version, so it's closable
