### ISSUE TITLE
[FEATURE] Add a PR template

### ISSUE THREAD

**Issue by kkhitesh** [EddieHubCommunity/api#206]
### ⭐ Suggestion

Add a PR template to the repository.

You can refer [here](https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/pull_request.md)

**Comment by ShaileshKumar007** [comment]
Let me work on this issue.

**Comment by kkhitesh** [comment]
Sure @ShaileshKumar007 go ahead and raise a PR.

@krishguptadev Sorry, please lookout for other issues 🙂
