### ISSUE TITLE
> Spike Put-Endpoints for Entities

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#212]
> When doing patch, the whole object should be replaced.

I believe the `PUT` method does this, not `PATCH`. I'm not familiar with the implementation but if the payload sent on the HTTP request only contains a few fields to update, then it should use the `PATCH` method.
From what I saw on the [calendar feature test](https://github.com/EddieHubCommunity/api/blob/main/test/features/calendar.feature), the `PUT` request doesn't send the fields `createdOn` and `updatedOn` so this should be indeed changed to `PATCH`.

In my opinion, Web APIs should strive to use `PUT` instead of `PATCH` whenever possible, simply because `PUT` is idempotent. Although `PATCH` can be idempotent depending on the implementation.

_Originally posted by @BOLT04 in https://github.com/EddieHubCommunity/api/issues/207#issuecomment-939474242_

**Comment by BOLT04** [comment]
this is still needed or not @Cahllagerfeld ?
