### ISSUE TITLE
Change License copyright to `Eddie Jaoude`

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/api#215]
Thanks everyone 👍 Makes sense. There is a mix across our Org repos, they should then be all updated to be `Eddie Jaoude`

_Originally posted by @eddiejaoude in https://github.com/EddieHubCommunity/awesome-github-profiles/issues/712#issuecomment-947703086_

**Comment by aroramrinaal** [comment]
@Cahllagerfeld , Can I work on this one?

**Comment by Cahllagerfeld** [comment]
Sure 👍

**Comment by aroramrinaal** [comment]
@Cahllagerfeld , I just opened a pull request for this #247

**Comment by eddiejaoude** [comment]
Thanks 👍
