### ISSUE TITLE
[OTHER] Migrate Datastax to MongoDB

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#217]
### What would you like to share?

The Modules in the api need to be migrated to MongoDB

- [x] #218
- [x] #219
- [x] #220
- [x] #221
- [x] #235
- [x] #225

**Comment by stemount** [comment]
Did we not collectively say that we do not want to use MongoDB? Or am I totally remembering this incorrectly.

MongoDB is fine if you use it with an ORM, but ultimately a Docker box with a mongodb or any DB service would be required.

**Comment by Cahllagerfeld** [comment]
To increase engagement we decided to rewrite the API and use Mongo. I think this issue can even be closed, as the new api with mongo is already live
