### ISSUE TITLE
[OTHER] Create DTO for DiscordEvents

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/api#228]
### What would you like to share?

Title says it all. 🙂

### Additional information

Nope.

**Comment by Panquesito7** [comment]
Ping?

**Comment by nhcarrigan** [comment]
What's a DTO?

**Comment by Panquesito7** [comment]
> What's a DTO?

> Data Transfer Object (model)

This is what Eddie said.

**Comment by Panquesito7** [comment]
Can someone remove the `no-issue-activity` label, please? Thanks. 😅
