### ISSUE TITLE
Create LinkFree Module

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#235]
for more context see #238 and #224

**Comment by krishguptadev** [comment]
What is the LinkFree module supposed to do? 🤔 

Manage profiles? Addition and stuff

**Comment by Cahllagerfeld** [comment]
See discussion here https://github.com/EddieHubCommunity/api/discussions/224#discussioncomment-1674416

**Comment by Cahllagerfeld** [comment]
Things to specify:

- [ ] name of the module
- [ ] which profiles will be allowed, im not a fan of having it as a generic object where someone can more or less add everything without our control
- [ ] use discord userid as id in the db, or will there be a other way for creating profiles?

**Comment by krishguptadev** [comment]
> Things to specify:
> 
> * [ ]  name of the module
> * [ ]  which profiles will be allowed, im not a fan of having it as a generic object where someone can more or less add everything without our control
> * [ ]  use discord userid as id in the db, or will there be a other way for creating profiles?

I think github usernames would be a better way to manage User IDs since I all of the users are using github ids and not discord (would be taunting to migrate)

**Comment by Cahllagerfeld** [comment]
Closing this for now. There shouldn't be a linkfree-Entity.
The Entity needs to be split in `users`, `milestone` and `social`
