### ISSUE TITLE
[FEATURE] Fix the COC!

### ISSUE THREAD

**Issue by krishguptadev** [EddieHubCommunity/api#241]
### ⭐ Suggestion

1. Update the version to: https://www.contributor-covenant.org/version/2/1/code_of_conduct/
2. Contact method: 
![image](https://user-images.githubusercontent.com/91655303/143671799-167734e7-73c0-45ff-882f-bbef8a3ec148.png)

**Comment by Saurabhpatil-dev** [comment]
Hey @krishguptadev ,

I would like to work on this. Can you please tell me where to make this changes?

**Comment by krishguptadev** [comment]
Can't assign (perm issues), but feel free to work on this!

**Comment by Saurabhpatil-dev** [comment]
Okay

**Comment by Cahllagerfeld** [comment]
Closed with #242
