### ISSUE TITLE
[OTHER] SECURITY POLICY

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/api#248]
### What would you like to share?

Add a security policy to report security vulnerabilities. This can be added by creating SECURITY.MD preferably in the .github directory.

Inculde url http://eddiejaoude.io/contact to report security issues

**Comment by Ash-KODES** [comment]
Why is build failing?

**Comment by KendallDoesCoding** [comment]
Please read comments in PR's
