### ISSUE TITLE
[BUG] Link to api.eddiehub.io returns Error 503

### ISSUE THREAD

**Issue by pandyaved98** [EddieHubCommunity/api#271]
### 🙁 Actual behavior

The link to the api.eddiehub.io mentioned under the About Section on this repository's README.md redirects to GitHub Pages' Error 503 (Service Unavailable) page.

### 🙂 Expected behaviour

The link should either redirect to a reachable interface or it should be mentioned that the interface might be unavailable or a work in progress as of now.

**Comment by Cahllagerfeld** [comment]
The API is reachable again with [https://api.eddiehub.io](https://api.eddiehub.io/). The 503 was a temporary issue during the deployment 👍
