### ISSUE TITLE
[FEATURE] GitHub events to come in via web hook

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#280]
### ⭐ Suggestion

The GitHub Action to send events to our EddieHub API is not working well with forks.

I just remembered that this might be done better with GitHub webhooks
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads

**Comment by eddiejaoude** [comment]
Sorry @Cahllagerfeld what do you think?

**Comment by Cahllagerfeld** [comment]
I never used Webhooks iwth Github, I need to dig into it a bit

**Comment by eddiejaoude** [comment]
I used it a long time ago, I am happy to pair on it if it helps.

I think the API endpoint will need to be tweaked a bit to accept the data in a slightly different format (IIRC it will just be the top level object fields but everything underneath will be the same)

**Comment by Cahllagerfeld** [comment]
Do we need to handle authentication for the webhook, or doesn't this matter? My concern is that people can just use the webhook by sending requests there and data gets created

**Comment by eddiejaoude** [comment]
The web hook on GitHub will be given a token from us to use to send with the data (similar to GitHub secrets), so it will be a protected request
https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks

**Comment by Cahllagerfeld** [comment]
# My Ideas

- Create an dedicated endpoint for webhook communication - I'd leave the existing one, in case we want to use it as a regular endpoint in the future for another scenario
- Create a new Guard that secures the Endpoint based on the link you shared earlier and [this gist](https://gist.github.com/stigok/57d075c1cf2a609cb758898c0b202428?permalink_comment_id=4052765#gistcomment-4052765)
- create new interface for the webhook payload - we potentially need to do a mapping here

**Comment by eddiejaoude** [comment]
Sounds like great ideas 👍

**Comment by eddiejaoude** [comment]
testing web hook

**Comment by eddiejaoude** [comment]
testing again
