### ISSUE TITLE
Husky pre commit check

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#29]
Make sure to use v5

- Lint commit messages with conventional commits http://conventionalcommits.org
- Lint code check 

https://www.npmjs.com/package/husky

**Comment by bagladivyang03** [comment]
@eddiejaoude I would like to contribute to this issue, Could u pls tell me what exactly has to be done for this issue.

**Comment by eddiejaoude** [comment]
@bagladivyang03 great 👍 

1. Install husky using "automatic installer" from their docs https://typicode.github.io/husky/#/?id=automatic-recommended
2. Add 2 hooks https://typicode.github.io/husky/#/?id=add-a-hook
   i. run linter
   ii. run tests
   iii.  run commit linter https://github.com/conventional-changelog/commitlint#getting-started

**Comment by bagladivyang03** [comment]
@eddiejaoude So basically I have to clone this repo and do all this in that directory?

**Comment by eddiejaoude** [comment]
You will need to 

- fork this repo on GitHub
- clone your fork locally
- create a branch locally

yep, then do the steps above in that directory 👍

**Comment by bagladivyang03** [comment]
@eddiejaoude Thanks :)

**Comment by bagladivyang03** [comment]
> @bagladivyang03 great 👍
> 
> 1. Install husky using "automatic installer" from their docs https://typicode.github.io/husky/#/?id=automatic-recommended
> 2. Add 2 hooks https://typicode.github.io/husky/#/?id=add-a-hook
>    i. run linter
>    ii. run tests
>    iii.  run commit linter https://github.com/conventional-changelog/commitlint#getting-started

Actually, I have installed husky using "automatic installer" after that I m getting confused about how to do that run linter and run test part i.e adding hooks
Could u pls help @eddiejaoude

**Comment by bagladivyang03** [comment]
@eddiejaoude I made a PR could u pls check that for this issue could u pls check :)

**Comment by Cahllagerfeld** [comment]
Theres a PR for this. Is this PR still relevant or do we need to do this again?

**Comment by eddiejaoude** [comment]
I think best probably to do it again 👍 we need this before people start to contribute

**Comment by Cahllagerfeld** [comment]
closed with #91
