### ISSUE TITLE
[BUG] Update Link in README

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/api#290]
### 🙁 Actual behavior

https://eddiehubcommunity.github.io/api/ -> 404

### 🙂 Expected behaviour

https://api.eddiehub.io/

**Comment by dev-divyansh** [comment]
hii , i want to work on this ;;

**Comment by ksaurabh4** [comment]
Seems it not fixed yet. So, I want to fix this @eddiejaoude if you allow.

**Comment by schmelto** [comment]
https://github.com/EddieHubCommunity/api/pull/294
