### ISSUE TITLE
[OTHER] Link to the documentation is not working https://eddiehubcommunity.github.io/api/

### ISSUE THREAD

**Issue by DeTexTeR-develop** [EddieHubCommunity/api#291]
### What would you like to share?

Link to the documentation for api is not working https://eddiehubcommunity.github.io/api/ . Getting 404 error, documentation not found.

**Comment by Cahllagerfeld** [comment]
I think the Documentation got removed while rewriting, lets remove it I guess. Wdyt @eddiejaoude?

**Comment by eddiejaoude** [comment]
Thanks @DeTexTeR-develop for letting us know 👍 

Where is the link used? 

@Cahllagerfeld I think you are right, best to remove it 👍

**Comment by DeTexTeR-develop** [comment]
@eddiejaoude it's in the readme, description section.

**Comment by DeTexTeR-develop** [comment]
@eddiejaoude if you want i can remove it

**Comment by eddiejaoude** [comment]
yes please 👍

**Comment by DeTexTeR-develop** [comment]
@eddiejaoude @Cahllagerfeld can you check the pr and merge it. I solved this issue few days ago
