### ISSUE TITLE
[OTHER] redundant return await affects performance  

### ISSUE THREAD

**Issue by jameslieu** [EddieHubCommunity/api#292]
### What would you like to share?

I've seen a few times `return await` is used outside try/catch blocks. This introduces a unnecessary microtask which impacts performance a little. 

This link explains this in some more detail
https://eslint.org/docs/latest/rules/no-return-await 

If you don't mind, I'd like to contribute and open a PR to remove `return await` from areas where they're used outside a try/catch block. Thanks

**Comment by jameslieu** [comment]
I've opened a PR for this but it was subsequently closed. I'll also close this issue as well

**Comment by eddiejaoude** [comment]
Thank you James!

We will geek out on some other issues/PR soon!
