### ISSUE TITLE
Setup the project

### ISSUE THREAD

**Issue by BOLT04** [EddieHubCommunity/api#3]
There has been some discussion about the technology choices for this project here: #1. So I was thinking we could get the project started and continue from there 😃.

The goal of this issue would be to bootstrap the project and get most stuff setup. So here are the tasks I purpose we complete:
- [ ] Setup a linter (e.g. ESLint)
- [ ] Setup Node.js w/TypeScript and Express
- [ ] Setup cucumber
- [ ] Setup MongoDB

**Comment by eddiejaoude** [comment]
Thanks @BOLT04 . This would be good. 👍

**Comment by sayand0122** [comment]
I read the issues of this project and i really feel its interesting so can someone give me ome insights on the things going on or completed?

**Comment by eddiejaoude** [comment]
There are 2 PRs already open for this:

- #4 setting up the project from scratch
- #5 a spike to see if `feathersjs` is a possible option

Both are still waiting for feedback from the community 🤓

**Comment by eddiejaoude** [comment]
We have broken this down into more specific issues, so I will close this.
