### ISSUE TITLE
Add Mongo DB for CRUD with typeorm 

### ISSUE THREAD

**Issue by khattakdev** [EddieHubCommunity/api#34]
Currently, the data is managed (CRUD) in Memory. 
It needs to be replaced with `typeorm` using `MongoDB`

**Comment by Cahllagerfeld** [comment]
Is it preffered to use Mongo in combination with [Nestjs/Mongoose](https://docs.nestjs.com/techniques/mongodb) or with [typeorm](https://docs.nestjs.com/techniques/database), which also provides an mongo-interface?

**Comment by eddiejaoude** [comment]
At the moment, we are deciding between Mongo and DataStax - we have a couple of PRs in draft to *spike* the differences

**Comment by Cahllagerfeld** [comment]
Okay this seems legit. Then waiting until we have more clarity on which DB to use is probably the best.

**Comment by Cahllagerfeld** [comment]
Is this still work-in-progress?
Otherwise I could do this spike on the weekend maybe

**Comment by eddiejaoude** [comment]
This is parked at the moment, because we are thinking of using DataStax as a DB #61 - I have a spike on this, I don't think I pushed it up yet though 🤦‍♂️

**Comment by Cahllagerfeld** [comment]
Okay, then we'll we will postpone this.
For this weekend we could think about doing a bigger issue though.

**Comment by eddiejaoude** [comment]
If you have time that would be great 👍 . You are super fast at these 💥 

What about #58 , I can add more of my ideas/thoughts around it to that ticket?

**Comment by Cahllagerfeld** [comment]
Yes, we could do that :D
Feel free to add your ideas 😄

**Comment by eddiejaoude** [comment]
Using AstraDB (Stargate)
