### ISSUE TITLE
Discord data collection

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#38]
**Discord**
```ts
interface Discord {
   uid: string;
   location: {
       text: string;
       lat: number;
       lng: number;
   };
   socials: {
       [key: string]: string; // GitHub, linkedin, instagram, twitter
   }
}
```

**Comment by Cahllagerfeld** [comment]
I think except the location we're having this module already implemented.
Are we going to need a Geocoding Service to turn real places into coordinates or can we expect the Client to send them?

**Comment by eddiejaoude** [comment]
Great question, we need to get the lat/lng, here is an example where we have done this before, but it will need moving to this project and module https://github.com/EddieHubCommunity/EddieBot/blob/ed49a8a3dd55d23b0e1d92bd09f2ea4f673993d8/src/commandHandlers/bio.ts#L128-L132

**Comment by Cahllagerfeld** [comment]
Okay I see this logic.
I suggest using the [nest-http-module](https://docs.nestjs.com/techniques/http-module). It is axios-based and uses observables out-of-the-box-

**Comment by eddiejaoude** [comment]
Sounds like a good idea 👍 , I like to keep things vanilla and go on the official recommended of the framework
