### ISSUE TITLE
Use Validatonpipe for DTOs

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#41]
Nest provides the opportunity to use [Validationpipe](https://docs.nestjs.com/techniques/validation) using `class-validator` and `class-transformer`.
Maybe we should think about using this pipe fot Data-Transfer-Objects.
Feel free to discuss on this topic.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion 👍 , sounds great 🤓

**Comment by Cahllagerfeld** [comment]
I'll add the validation to the existing modules which currently dont get validated in #73 as its probably a small fix.
