### ISSUE TITLE
GitHub data collection

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#44]
**GitHub**

```ts
interface GitHub {
   username: string;
   bio: string; // do we need Discord bio?
   avatarUrl: string
   followers: number;
   repos: number;
   // ... any other useful info public info https://docs.github.com/en/rest/reference/users
   communityStats: {
      [key: string]: number
   };
}
```

Also playing with https://github.com/EddieHubCommunity/api/issues/61

**Comment by Cahllagerfeld** [comment]
Is this Issue meant as a Github-Integration within the Nest-App?

**Comment by eddiejaoude** [comment]
Oh sorry just seeing this notification now. We have a GitHub Action that will send stats from our community Org Repos to our API

**Comment by Cahllagerfeld** [comment]
Thats nice! Luckily we dont have to handle different Accesstokens for different users then.

**Comment by Cahllagerfeld** [comment]
I'll start working on this. You can assign this Issue to me if you want.

**Comment by eddiejaoude** [comment]
Great, thanks 👍 . Sure assigned 🎉

**Comment by Cahllagerfeld** [comment]
> 
> 
> **GitHub**
> 
> ```ts
> interface GitHub {
>    username: string;
>    bio: string; // do we need Discord bio?
>    avatarUrl: string
>    followers: number;
>    repos: number;
>    // ... any other useful info public info https://docs.github.com/en/rest/reference/users
>    communityStats: {
>       [key: string]: number
>    };
> }
> ```
> 
> Also playing with #61

Hi Eddie, could you please specify which of the properties are mandatory, and which of them are optional?
Thank you! :D

**Comment by eddiejaoude** [comment]
Thanks for the questions @Cahllagerfeld , here are my thoughts...

> could you please specify which of the properties are mandatory, and which of them are optional?

I think the `username` is the only required property

> Will we accept any Key, Value pairs in communityStats Object, or do we need to specify this more?

Ideally we should specify these, and do a check that it is in our allowed list. The list will come from GitHub events, here is the [example usage](https://github.com/EddieHubCommunity/gh-action-community/blob/develop/src/statistics/index.js#L16) for where the data will come from, and here are the [docs](https://docs.github.com/en/actions/reference/events-that-trigger-workflows) for the list of events

 > Should we implement the Validationpipe mentionend in #41?

I think that would be great 👍 , it would allow us to re-use the validation in multiple places

**Comment by Cahllagerfeld** [comment]
I'll adjust these things and update the PR then.

**Comment by eddiejaoude** [comment]
Amazing, thank you 👍 - great questions ❤️

**Comment by Cahllagerfeld** [comment]
I'm currently coding the TypeValidation for the DTO, but I'm still not getting the community stats completly I think.
Is this an object in which the properties are github-events or am I getting this wrong?

Could you explain it again pls? :sweat:

**Comment by eddiejaoude** [comment]
Sure, no problem 👍 sorry for not being clear

> Is this an object in which the properties are github-events

yes you are correct - each time an event happens, the GitHub Action will send the event name and our API needs to increment it. Thinking about it before with Firebase, the Firestore DB did the increment, but our API will need to do it now

So I think the request from the GitHub Action can be

```ts
// POST
{
   // ...
   event: {
       issues: true
   }
}
```

Then we should increment the `issues` property by 1.

I am open to suggestions if you can think/see any improvements 🤓

**Comment by Cahllagerfeld** [comment]
I think I got it now. My first thought would be, that mapping the value is probably the best idea. 
I'll think about it tomorrow if this could be optimizable at some point.
