### ISSUE TITLE
Deploy to EddieHub Kubernetes cluster using GitHub Actions

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#50]
Example in http://github.com/eddiejaoude/stargate

**Comment by Cahllagerfeld** [comment]
Need a fix for using GHPR for building the Docker-Image

**Comment by Cahllagerfeld** [comment]
I can have a look at this `npmrc`-Problem when building the image. Is there a way on how to test this without making 100 commits to `main`?

**Comment by eddiejaoude** [comment]
> I can have a look at this npmrc-Problem when building the image

thank you! this is on my list but I did not get round to it yet

> Is there a way on how to test this without making 100 commits to main?

Wit could be done in a branch and the Action trigger could be updated temporarily for that branch

**Comment by Cahllagerfeld** [comment]
Sounds legit. 
I'll have a look at this then

**Comment by eddiejaoude** [comment]
Here is an example I am trying, I did a temporary update to the Action trigger https://github.com/EddieHubCommunity/api/pull/115

**Comment by eddiejaoude** [comment]
This was the commit, because now I removed the temporary code, the PR link won't make sense 🤦‍♂️ https://github.com/EddieHubCommunity/api/pull/115/commits/d079a40aa334620324dec7c15e8ee69535d1fe60

**Comment by Cahllagerfeld** [comment]
I think this is working now isnt it?

**Comment by eddiejaoude** [comment]
Oh yes this is done, thank you, I will close 👍

**Comment by schmelto** [comment]
Consider moving the issue in the project board.
