### ISSUE TITLE
REST-API-Design-Guideline

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#55]
We could think about using a Rest-Api-Design-Guideline like [this](https://github.com/NationalBankBelgium/REST-API-Design-Guide/wiki) for designing out endpoints consistently

**Comment by eddiejaoude** [comment]
I really like this 👍 , we can get out of it from the recommendations from NestJS docs, as I like to keep this vanilla to the recommendations of the framework, so that it is easier to onboard new people
