### ISSUE TITLE
Idea: Calendar Module

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#58]
In case of having a "Community Calendar" we could integrate this to the Api, to access Data from that Calendar in other projects as well.
Before realizing that we should definitly specify some more Details - Feel free to Add Ideas in the Comments!

**Comment by eddiejaoude** [comment]
I think this would be great 👍 

The Discord bot could read/write to this to add / list events, and the web ui could list the events on a web page

On the list api end-point, it should only return up and coming events, other the list will get too long

**Comment by eddiejaoude** [comment]
The calendar data might look like

```ts
{
   name: string;
   description: string;
   url: string;
   platform: "YouTube" | "Twitch"; // we should only have an allowed list
   author: {
      platform: "discord" | "github"; // these events could be created via the discord bot or a GitHub Action triggered by an issue
      uid: string
   };
   startDate: Date;
   endDate: Date;
}
```

Notes:
- future: on the `GET` the list should only bring back current events going on and future events
- history: another idea is to have a parameter on the `GET` to be able to retrieve historic events, but this can come later on in another PR
- delete can only be by the same author (in the future by admin but we have no admin facility for this yet)

**Comment by Cahllagerfeld** [comment]
Is the `uid` in the `author-object` generated by the api or sent by the client? I'm not 100% clear what uid this is 😅

**Comment by eddiejaoude** [comment]
In my mind (which could be wrong), I was thinking of the `uid` being the user object from their respect platforms, so in the Discord Bot it would send through their Discord unique identifier and on the GitHub Action it would be their GitHub username - only approved apps can send through the data, so I think we can trust this data?

**Comment by Cahllagerfeld** [comment]
Oh now I get it :D I thought about using the `uuid`-package for this.
I think you are right, with the Authentication we can trust the provided data.
I think we need to add an `id` for the actual calendar-object as well. 
Do we need info about `created` or `updated`?

**Comment by Cahllagerfeld** [comment]
When doing the date calculations which event is in the past, which one is ongoing and which one is the future, I'd like to use a third-party package for that. I really enjoy using `date-fns` when it comes to this.
Is this okay for you?

**Comment by eddiejaoude** [comment]
> I think we need to add an id for the actual calendar-object as well.
> Do we need info about created or updated?

Good point, yes and yes 👍 

> I really enjoy using date-fns when it comes to this.

Good idea 👍

**Comment by Cahllagerfeld** [comment]
![image](https://user-images.githubusercontent.com/43843195/115891654-9b06f800-a456-11eb-89d1-9a9712f4ddc7.png)
I implemented the response for the `getAll`-Endpoint like shown above:
- The Events are already sorted in future and ongoing, so the client doesnt need to implement this logic.
- When using a database we should define the timeranged before making the request and not filtering like here. Otherwise we have to read **ALL** Entries for events that have ever been made and this may be a huge payload.
