### ISSUE TITLE
Documentation: Add Swagger to the API

### ISSUE THREAD

**Issue by BOLT04** [EddieHubCommunity/api#6]
To document our API, using Swagger and the OpenAPI specification will benefit us since it's a known standard in the industry. I don't think we'll have a hypermedia API, so there is no need to worry about documenting the URLs.

We can have a look at this: https://github.com/feathersjs-ecosystem/feathers-swagger.

Let me know what other suggestions you have for documentation and what you think 😃

**Comment by eddiejaoude** [comment]
Good idea 👍 - this should be added to the open PR, so that we have a PR that contains our minimum standards.

**Comment by mstanciu552** [comment]
I will look into it tomorrow and start implementing.

**Comment by Vyvy-vi** [comment]
@mstanciu552 I think this is currently being addressed in the open PR: #5 
Perhaps, you could open a PR directly to the `featherjs` branch after task 7th on the list is completed?

**Comment by eddiejaoude** [comment]
@Vyvy-vi 👍 

@mstanciu552 how did you get on?

**Comment by mstanciu552** [comment]
Sorry it might be the late hour I'm reading this at, but do you mean how did it get on to open a PR for the `featherjs` branch or how did it go with the swagger documentation? 😋

**Comment by eddiejaoude** [comment]
No worries @mstanciu552 . I am still catching up on GitHub notifications.

> I will look into it tomorrow and start implementing.

I was asking about your previous comment, but no stress / rush

**Comment by mstanciu552** [comment]
Oh ok. I looked into swagger and it seems like a grea resource, but I didn't find the time to implement it in order to test it.

**Comment by eddiejaoude** [comment]
No problem 🤓
