### ISSUE TITLE
Run DataStax locally with Docker Compose

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#61]

**Comment by Cahllagerfeld** [comment]
Did you already manage to connect your local Docker-Stargate-Instance to [this](https://www.npmjs.com/package/@astrajs/collections) package?

I feel like documentation is quite poor for this, as there arent even types provided for this package. :(

**Comment by eddiejaoude** [comment]
Yes I finally managed connect to it locally as well as remotely with config, but it was difficult to figure out. Here is my latest commit on it in a branch https://github.com/EddieHubCommunity/api/commit/0b9c7b1d1748088214894af86b652ed999a17fab

**Comment by Cahllagerfeld** [comment]
[Link](https://github.com/Cahllagerfeld/nestjs-astra-module) to potential Module for Connecting to Datastax Astra. 
Should we migrate the repo to Eddiehub as soon as its working?

**Comment by eddiejaoude** [comment]
> Should we migrate the repo to Eddiehub as soon as its working?

Sounds good 👍

**Comment by Cahllagerfeld** [comment]
I'd say the module is ready for a test with this project.
The module isnt providing every single option yet, but we should get it up and running with the API.
Would you test it locally with `npm link` first, or would you make a initial release and test it with the built npm-github-package?

**Comment by eddiejaoude** [comment]
> Would you test it locally with npm link first, or would you make a initial release and test it with the built npm-github-package?

good question, I think let's do it with a built package

**Comment by Cahllagerfeld** [comment]
> 
> 
> > Would you test it locally with npm link first, or would you make a initial release and test it with the built npm-github-package?
> 
> good question, I think let's do it with a built package

Okay, I think the best way of doing this is setting up a Action which builds the package on release, isnt it?
I need to do some research on using Github Registry for npm-packages first.

**Comment by Cahllagerfeld** [comment]
How should we go on now?
I tested the module successfully with a real DataStax Astra Instance.
Do we migrate the repo, or leave it for now?
Shall I already start implementing the module in the modules or do you see any steps that need to be made before implementing it?

**Comment by Cahllagerfeld** [comment]
Is this still open?

**Comment by eddiejaoude** [comment]
This is done now, yep we can close 👍
