### ISSUE TITLE
Remove location from Discord models

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/api#66]
Location will come from GitHub data, no need for the user to set it via the Discord Bot

**Comment by Cahllagerfeld** [comment]
I think its best if we do this issue next.
Feel free to assign it to me!

**Comment by Cahllagerfeld** [comment]
If we leave the PR for this issue as it is.
What would you prioritize next?

**Comment by eddiejaoude** [comment]
I think authentication would be good to tackle next, what do you think?

**Comment by Vyvy-vi** [comment]
Yes, that would be great. I think we can maybe make an auth app for both Discord and Github?

**Comment by Cahllagerfeld** [comment]
Yes I think an Auth-Module for Discord, and Github-Service as mentioned in #51 would be best.
@Vyvy-vi if you want we can collaborate on this. Eddie and my even had some thoughts about implementing this.

**Comment by eddiejaoude** [comment]
I think both will be the same with server to server comms?

**Comment by Cahllagerfeld** [comment]
Yes, I think so. But I suggest using two different tokens for discord bot and github action. Otherwise we may have some bad side-effects - when one token gets hijacked for example. Then 'only' Discord or Github is vulnerable, not both at once

**Comment by eddiejaoude** [comment]
Yes I agree, each app should have its own token 👍

**Comment by Vyvy-vi** [comment]
I think leveraging Github's and Discord's Oauth might be better?
Here's a process flow we can consider-
```
user[bot-command]> ^verify
EddieBot/Other Bot> Dm's a site link(maybe a version EddieHub UI or something)
The site> It's at `join.eddiehub.org/id?={user-id(from discord)}&token={temp-token-that-expires-in-an-hour}`
                 Has 2 buttons -> Verify GIthub
                                          -> Verify Discord
The buttons> Use github and discord's oauth apis to log in the user on that site, and store relevant info to the db. For extra verification, the user id from the discord oauth can be matched to the id given by the request. All this gets written to db, after it checks that the token give is valid.
```

**Comment by Vyvy-vi** [comment]
I think this way we don't need to deal with multiple tokens, since the oauth verification just has the user log into the site using both of them and uses the tokens internally(might make our work easier)
Discord Oauth docs- https://discord.com/developers/docs/topics/oauth2

**Comment by eddiejaoude** [comment]
Good idea, but in this situation I think we need to verify the app not the person.

For example
- Discord bot: will allow everyone to read/write via the bot because they will need a discord account to use the bot, then we just need to verify the bot has write access to the API - so no one can trick it
- GitHub Action: will allow everyone to read/write via the Action because they need a GitHub account to trigger the action
- Map UI: will only need readonly to the API

I hope that makes sense?

**Comment by Vyvy-vi** [comment]
oh, I think we're talking about two different things

**Comment by Cahllagerfeld** [comment]
I think we should discuss these things in #51 tbh 😅 
If we really want to do OAuth, theres the `Client-Credential-Flow` for `m2m`-Communication if I remember corretly
