### ISSUE TITLE
Documentation for setting up MongoDB

### ISSUE THREAD

**Issue by mstanciu552** [EddieHubCommunity/api#7]
We should add some documentation for setting up mongo for running this locally, related to the project, of course.
We should also add a link to the [MongoDB](https://www.mongodb.com/) official page for more instructions.

Share your opinion about this.

**Comment by Vyvy-vi** [comment]
I think Mongo hasn't been implemented _yet_.
However, once it's implemented, having docs for how to set mongo for a local instance, would be great 👍 

Additional Context: Setting up mongo DB is a due task, referenced in issue #3

**Comment by mstanciu552** [comment]
Well MongoDB was set up but only for Eddie's `featherjs` branch.

I also have a question. Why is the featherjs branch not in the main branch?

Are we still choosing a stack or waiting for someone to set up a normal `express` project?

**Comment by BOLT04** [comment]
@mstanciu552 we haven't merged since we were trying to complete most checkboxes on the PR (currently missing only swagger docs). But the stack is Feather.js 😃 with TypeScript

**Comment by mstanciu552** [comment]
I just looked into it and I think it's not that time consuming to set up swagger so I will get started on testing it tomorrow.
👍

**Comment by eddiejaoude** [comment]
Also, I would like to add to that branch Docker + Docker Compose, so people do not need to worry about setting up the DB and it should "just work" - famous last words 😂

**Comment by eddiejaoude** [comment]
I will close this, as it will be a `compose up` for the DB which ever one we decide on
