### ISSUE TITLE
Bug: Geocoding causes Crash when not providing valid Location

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#70]
The API crashes when no real Data is returned from the geocoding-Service.

I suggest adding `try-catch` adding to it.

**Comment by eddiejaoude** [comment]
Good idea 👍 . Yep if no data is returned I think we can return a `400` error and the requesting app can decide what to do with the  error

**Comment by Cahllagerfeld** [comment]
Thats a quite small bug. I'll fix this in #69

**Comment by eddiejaoude** [comment]
Thank you!!
