### ISSUE TITLE
Refactor DTOs to make them consistent

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#71]
We should refactor the DTOs, so they have a consistent naming convention.
![grafik](https://user-images.githubusercontent.com/43843195/115518031-0cdd1700-a288-11eb-8097-15af42b8300a.png)

**Comment by eddiejaoude** [comment]
Oh yes, I really don't like inconsistency. Thank you for raising 👍

**Comment by Cahllagerfeld** [comment]
I think we should do that after the Auth-Thing is merged

**Comment by eddiejaoude** [comment]
Yep, makes sense 👍

**Comment by Cahllagerfeld** [comment]
After the huge new Auth-Module I think we should start a short stabilization phase where we do the open refactor(like this one) and bug issues, before implementing new features. 
How would you see that?

**Comment by eddiejaoude** [comment]
Sounds like a good plan 👍 

I agree, I think the refactoring is a higher priority than new features - so that it can have a good foundation 💪

**Comment by Cahllagerfeld** [comment]
Thats true, the foundation gets more and more important as everything grows.
You can assign this ticket to me then.
