### ISSUE TITLE
Idea: Rate Limiting

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#72]
Do we need rate-limiting for the api, that we cant get ddosed?
We could set how many requests in a specific interval are served directly, while the additional ones are delayed automatically.

**Comment by eddiejaoude** [comment]
This would be a good idea, to protect the API 👍 

Any suggestions on numbers?

**Comment by Cahllagerfeld** [comment]
I dont have a real idea how many requests we can or should expect.
Its probably a thing we can implement with any default values and adjust them later as we see the frequency the api is used maybe?

**Comment by eddiejaoude** [comment]
sounds good 👍

**Comment by bineetNaidu** [comment]
Is anyone working on it :smiley:  ??

**Comment by Cahllagerfeld** [comment]
As far as I know isnt this assigned to anyone.
