### ISSUE TITLE
Connect Module to Datastax Astra

### ISSUE THREAD

**Issue by Cahllagerfeld** [EddieHubCommunity/api#85]
The actual Database needs to be connected to our API

**Comment by Cahllagerfeld** [comment]
I think this issue will lead to a few more. 
- [ ] remove hardcoded Ids 
- [ ] remove hardcoded dates
- [ ] adjust step-definitions to unknown-values like `id` or `date`
- [ ] adjust github actions for stargate-testing


I think this PR might get a bit bigger then.
Do you want to do all modules at once, or start with `standup` for example?

**Comment by eddiejaoude** [comment]
I think most of those could go in a new PR, to try and keep PRs small. Maybe each module could be done in its own PR?

**Comment by Cahllagerfeld** [comment]
Sure! lets do it like this 👍
